### ISSUE TITLE
not plug-and-play; doesn't start

### ISSUE THREAD

**Issue by mintty** [goreliu/wsl-terminal#2]
Thanks for making such a package at all; however, it has some non-standard preconditions.
ahk is not a standard file extension and not installed here, so it does not work.

**Comment by goreliu** [comment]
I compile *.ahk to *.exe in build.bat (and download ahk2exe in prepare.sh),  wsl-terminal-ver.7z only include *.exe.

**Comment by mintty** [comment]
I see. I hadn't noticed the first time that build.bat failed to run that because after unpacking under cygwin, the tools don't have execute permission. Setting chmod +x doesn't work either because next time the files are freshly unzipped. Running build.bat from cmd.exe doesn't work either because there is no unzip.

If I fix these issues manually, open-wsl.exe fails with an error popup:
```
---------------------------
open-wsl.exe
---------------------------
Error:  Failed attempt to launch program or document:
Action: <C:\cygwin\home\towo\wsl-terminal-master\src\bin\mintty -t "        " -e /bin/wslbridge -t "bash>
Params: <>

Specifically: Das System kann die angegebene Datei nicht finden.

	Line#
--->	015: Run,%A_ScriptDir%\bin\mintty -t "%title%" -e /bin/wslbridge -t "%shell%

The current thread will exit.
---------------------------
OK   
---------------------------
```

**Comment by goreliu** [comment]
I have no Cygwin/MSYS2 installed, build.sh will run *.sh with /bin/bash in WSL, and default permissions of all files are 0777. wget/tar/xz/gzip/unzip/p7zip should be installed before running build.sh.

After running build.sh, chdir to C:\cygwin\home\towo\wsl-terminal-master\output, and run open-wsl.exe,  instead of C:\cygwin\home\towo\wsl-terminal-master\src\open-wsl.exe. Maybe I should remove *.exe from src directory.

**Comment by mintty** [comment]
There is no wsl-terminal-master\output directory; the source package does not build without additional dependencies or/and manual intervention in any environment (cygwin, WSL, cmd). In a plain Windows cmd window, e.g., it fails because there is no unzip. A script build.sh does not exist. Not sure how the source package is supposed to be built.

[Maybe I should create separate issues, but let me summarize my findings once more for now]

About the binary package: The howto says "download and run open-wsl" but that does not work because it needs to be unpacked first which does not work on a plain system because 7z is not part of a plain standard system configuration. I suggest to avoid such dependencies.

About the package contents: open-wsl displays a mintty popup:
```
/usr/bin/mintty: could not load icon file '/Cygwin-Terminal.ico':
```
then runs WSL in the current directory.

Major use cases are not addressed yet:
* How to start terminal from WSL?
* How to start terminal with login bash, in home dir?
* How to start terminal from desktop shortcut?
* How to configure an icon; maybe some kind of overlay of the WSL icon (which is round on transparent background) on the mintty terminal icon might be nice.
About the latter, I will add a comment in the respective mintty issue https://github.com/mintty/mintty/issues/558

**Comment by goreliu** [comment]
If `wsl-terminal-master\output` is not exit, build.bat failed to run. I add some error messages (https://github.com/goreliu/wsl-terminal/commit/d19e990c7bfc1d08c103f40d25fc1f3cb9dfc4d6). WSL (instead of Cygwin) is depended to run build.bat, make sure build.bat will call C:\Windows\System32\bash.exe (or C:\Windows\SysNative\bash.exe), instead of C:\Cygwin64\bin\bash.exe.

And I add a zip package (https://github.com/goreliu/wsl-terminal/commit/446a7836609b4cb84cda3d0ef42465f87d32e1ad).

open-wsl will not display a mintty popup:

```
/usr/bin/mintty: could not load icon file '/Cygwin-Terminal.ico':
``

Because open-wsl call /bin/mintty instead of /usr/bin/mintty, and it will not find Cygwin-Terminal.ico.

**Comment by goreliu** [comment]
> How to start terminal from WSL?

The only way is using wstart, `wstart open-wsl`.

> How to start terminal with login bash, in home dir?

To start terminal with login bash, set `shell=bash -l` in etc/wsl-terminal.conf (https://github.com/goreliu/wsl-terminal/commit/bff5ee0bc0599cbb6c0f67383f60896e62813b35 fix it).
To start in home dir, add `cd $HOME` in .bash_profile, and I will think other ways.

> How to start terminal from desktop shortcut?

Create a shortcut to open-wsl.exe in explorer.exe.

**Comment by goreliu** [comment]
I will add a `icon=` config in wsl-terminal later.

I use  %LOCALAPPDATA%\lxss\bash.ico in run-wsl-file.exe because if a file is associated with run-wsl-file.exe, bash.ico seems better then a AutoHotKey icon (a letter "H"). It may cause a copyright issue, I will find other ways, or find another icon.

**Comment by goreliu** [comment]
I have replaced all icons of *.exe (https://github.com/goreliu/wsl-terminal/commit/818cc5ddb1d0832cd0e8d4be532af752304f69d0, https://github.com/goreliu/wsl-terminal/commit/f0b8c0ff8872f8a5feba73c93c2b0bb39780d1fd), I downloaded them from http://www.iconfont.cn, they are free-to-use images.

**Comment by mintty** [comment]
I may have been misleading about the icon; I think referring to %LOCALAPPDATA%\lxss\bash.ico is a good choice as long as mintty has no icon overlay feature (i.e. combining the bash icon with its own dynamically). (The idea of such a feature is to avoid inclusion of any bash.ico-derived file in the package.)

About `wstart open-wsl`, `bash -l`, and a desktop shortcut, these were rather meant as suggestions to polish the package as to provide basic features out-of-the-box for less-expert users. I know it's fiddly to optimize a package to that aim and may take some time. I'm also considering to provide a very basic package myself, which you will be welcome to reuse for your more enhanced package.
