### ISSUE TITLE
Any way to "pin to taskbar"?

### ISSUE THREAD

**Issue by LeoLozes** [goreliu/wsl-terminal#44]
First of all thanks for this great terminal! 
The only "problem" I have is that I didn't find a way to pin it to the Windows 10 Taskbar.
I did use the utility to pin it to start and it works nicely, but when I try to pin it to the Taskber either it doesn't work or when I click, it opens in another icon. 

Any ideas on how to do it? Thanks!

**Comment by goreliu** [comment]
`open-wsl.exe` is only a starter of `mintty.exe`, so you can pin `mintty.exe` instead of `open-wsl.exe` to Taskbar, but it's a little difficult.

Create a shortcut of `mintty.exe`, and then change the properties of the .lnk file, add ` /bin/wslbridge -t bash` to the target (it won't read `etc/wsl-terminal.conf`), and change the icon to `open-wsl.exe`, then pin this .lnk file to Taskbar.

**Comment by LeoLozes** [comment]
Great! Worked beautifully, thanks!

**Comment by accesspc** [comment]
A big thanks from me too!
My solution to "Pin to taskbar":
* Create a shortcut of open-wsl.exe in the same directory
* Rename it to WSL
* Modify link so that target would have additional " -l" at the end
* Right click and Pin to taskbar

This way the taskbar icon is alway clear, once you click it it spawns a new window. If you have multiple WSL windows, they are grouped under a new taskbar icon and the pinned one is always free and ready to spawn another window with a single click.

**Comment by shashankgandham** [comment]
@goreliu After following your solution, it runs default ubuntu terminal and not wsl-terminal

**Comment by ssshake** [comment]
Looks like I reported a duplicate of this yesterday. I'm wondering instead of providing instructions to do this could a solution be to provide this shortcut in the zip itself, save people the trouble?

**Comment by goreliu** [comment]
I fixed it in [v0.8.9](https://github.com/goreliu/wsl-terminal/releases/tag/v0.8.9).
